//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeonSignWPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_order { get; set; }
        public int id_user { get; set; }
        public int id_neon_type { get; set; }
        public int id_color { get; set; }
        public int id_form { get; set; }
        public Nullable<int> total_price { get; set; }
    
        public virtual NeonColor NeonColor { get; set; }
        public virtual NeonType NeonType { get; set; }
        public virtual SignForm SignForm { get; set; }
        public virtual Users Users { get; set; }
    }
}
